export { default as Main } from './Main'
export { default as Auth } from './Auth'
export { default as SignUp } from './SignUp'
export { default as Dashboard } from './Dashboard'
export { default as UserPage } from './UserPage'
